import type { Transaction } from "./transaction-schema";

export const transactionStatuses = [
  { label: "Completed", value: "completed", color: "text-green-500" },
  { label: "Pending", value: "pending", color: "text-yellow-500" },
  { label: "Processing", value: "processing", color: "text-blue-500" },
  { label: "Failed", value: "failed", color: "text-red-500" },
  { label: "Refunded", value: "refunded", color: "text-purple-500" },
  { label: "Disputed", value: "disputed", color: "text-orange-500" },
];

export const paymentMethods = [
  { label: "Credit Card", value: "credit_card" },
  { label: "Debit Card", value: "debit_card" },
  { label: "Bank Transfer", value: "bank_transfer" },
  { label: "Digital Wallet", value: "digital_wallet" },
  { label: "Cryptocurrency", value: "crypto" },
  { label: "ACH Transfer", value: "ach" },
];

export const gateways = [
  { label: "Stripe", value: "stripe" },
  { label: "PayPal", value: "paypal" },
  { label: "Square", value: "square" },
  { label: "Adyen", value: "adyen" },
  { label: "Braintree", value: "braintree" },
];

export const transactions: Transaction[] = [
  {
    id: "txn_1",
    reference: "PAY-2024-00001",
    customer: {
      name: "Emma Thompson",
      email: "emma.thompson@company.io",
      avatar: "https://github.com/shadcn.png",
    },
    amount: 4299.0,
    currency: "USD",
    status: "completed",
    method: "credit_card",
    gateway: "stripe",
    country: "United States",
    createdAt: "2024-11-28T14:32:00Z",
    completedAt: "2024-11-28T14:32:45Z",
    fee: 128.97,
    net: 4170.03,
    riskScore: 12,
    description: "Enterprise Plan - Annual",
  },
  {
    id: "txn_2",
    reference: "PAY-2024-00002",
    customer: {
      name: "Marcus Chen",
      email: "m.chen@enterprise.com",
      avatar: "https://github.com/leerob.png",
    },
    amount: 12850.0,
    currency: "USD",
    status: "processing",
    method: "bank_transfer",
    gateway: "adyen",
    country: "Singapore",
    createdAt: "2024-11-28T14:15:00Z",
    fee: 25.7,
    net: 12824.3,
    riskScore: 8,
    description: "Bulk License Purchase",
  },
  {
    id: "txn_3",
    reference: "PAY-2024-00003",
    customer: {
      name: "Sarah Williams",
      email: "sarah.w@startup.io",
      avatar: "https://github.com/evilrabbit.png",
    },
    amount: 890.5,
    currency: "USD",
    status: "completed",
    method: "digital_wallet",
    gateway: "paypal",
    country: "United Kingdom",
    createdAt: "2024-11-28T13:45:00Z",
    completedAt: "2024-11-28T13:45:12Z",
    fee: 26.72,
    net: 863.78,
    riskScore: 5,
    description: "Pro Plan - Monthly",
  },
  {
    id: "txn_4",
    reference: "PAY-2024-00004",
    customer: {
      name: "James Rodriguez",
      email: "j.rodriguez@corp.net",
      avatar: "https://github.com/rauchg.png",
    },
    amount: 2340.0,
    currency: "USD",
    status: "pending",
    method: "debit_card",
    gateway: "stripe",
    country: "Mexico",
    createdAt: "2024-11-28T12:30:00Z",
    fee: 70.2,
    net: 2269.8,
    riskScore: 25,
    description: "Team Plan Upgrade",
  },
  {
    id: "txn_5",
    reference: "PAY-2024-00005",
    customer: {
      name: "Lisa Park",
      email: "lisa.park@tech.co",
      avatar: "https://github.com/timneutkens.png",
    },
    amount: 5670.0,
    currency: "USD",
    status: "failed",
    method: "credit_card",
    gateway: "braintree",
    country: "South Korea",
    createdAt: "2024-11-28T11:20:00Z",
    fee: 0,
    net: 0,
    riskScore: 78,
    description: "Enterprise Plan - Quarterly",
  },
  {
    id: "txn_6",
    reference: "PAY-2024-00006",
    customer: {
      name: "David Kim",
      email: "d.kim@solutions.io",
      avatar: "https://github.com/shuding.png",
    },
    amount: 1299.0,
    currency: "USD",
    status: "refunded",
    method: "credit_card",
    gateway: "stripe",
    country: "Canada",
    createdAt: "2024-11-28T10:15:00Z",
    completedAt: "2024-11-28T10:16:00Z",
    fee: -38.97,
    net: -1260.03,
    riskScore: 15,
    description: "Refund - Service Cancellation",
  },
  {
    id: "txn_7",
    reference: "PAY-2024-00007",
    customer: {
      name: "Olivia Martinez",
      email: "o.martinez@global.com",
      avatar: "https://github.com/vercel.png",
    },
    amount: 8750.0,
    currency: "USD",
    status: "completed",
    method: "ach",
    gateway: "stripe",
    country: "United States",
    createdAt: "2024-11-28T09:45:00Z",
    completedAt: "2024-11-28T09:48:00Z",
    fee: 5.0,
    net: 8745.0,
    riskScore: 3,
    description: "Annual Subscription Renewal",
  },
  {
    id: "txn_8",
    reference: "PAY-2024-00008",
    customer: {
      name: "Alexander Petrov",
      email: "a.petrov@techfirm.ru",
      avatar: "https://github.com/nextjs.png",
    },
    amount: 3420.0,
    currency: "USD",
    status: "disputed",
    method: "credit_card",
    gateway: "adyen",
    country: "Germany",
    createdAt: "2024-11-27T16:30:00Z",
    completedAt: "2024-11-27T16:31:00Z",
    fee: 102.6,
    net: 3317.4,
    riskScore: 65,
    description: "Disputed - Unauthorized Transaction",
  },
  {
    id: "txn_9",
    reference: "PAY-2024-00009",
    customer: {
      name: "Aisha Hassan",
      email: "aisha.h@innovate.ae",
      avatar: "https://github.com/tailwindlabs.png",
    },
    amount: 15600.0,
    currency: "USD",
    status: "completed",
    method: "bank_transfer",
    gateway: "adyen",
    country: "United Arab Emirates",
    createdAt: "2024-11-27T14:20:00Z",
    completedAt: "2024-11-27T14:25:00Z",
    fee: 31.2,
    net: 15568.8,
    riskScore: 7,
    description: "Enterprise Agreement",
  },
  {
    id: "txn_10",
    reference: "PAY-2024-00010",
    customer: {
      name: "Hiroshi Tanaka",
      email: "h.tanaka@tokyo-corp.jp",
      avatar: "https://github.com/radix-ui.png",
    },
    amount: 6890.0,
    currency: "USD",
    status: "completed",
    method: "credit_card",
    gateway: "stripe",
    country: "Japan",
    createdAt: "2024-11-27T11:10:00Z",
    completedAt: "2024-11-27T11:10:30Z",
    fee: 206.7,
    net: 6683.3,
    riskScore: 10,
    description: "Multi-seat License",
  },
  {
    id: "txn_11",
    reference: "PAY-2024-00011",
    customer: {
      name: "Priya Sharma",
      email: "priya.s@techstart.in",
      avatar: "https://github.com/shadcn.png",
    },
    amount: 450.0,
    currency: "USD",
    status: "completed",
    method: "digital_wallet",
    gateway: "paypal",
    country: "India",
    createdAt: "2024-11-27T09:30:00Z",
    completedAt: "2024-11-27T09:30:15Z",
    fee: 13.5,
    net: 436.5,
    riskScore: 4,
    description: "Starter Plan - Monthly",
  },
  {
    id: "txn_12",
    reference: "PAY-2024-00012",
    customer: {
      name: "Lucas Andersson",
      email: "l.andersson@nordic.se",
      avatar: "https://github.com/leerob.png",
    },
    amount: 2100.0,
    currency: "USD",
    status: "pending",
    method: "bank_transfer",
    gateway: "adyen",
    country: "Sweden",
    createdAt: "2024-11-27T08:45:00Z",
    fee: 4.2,
    net: 2095.8,
    riskScore: 12,
    description: "Professional Plan - Annual",
  },
  {
    id: "txn_13",
    reference: "PAY-2024-00013",
    customer: {
      name: "Chen Wei",
      email: "c.wei@shenzhen-tech.cn",
      avatar: "https://github.com/evilrabbit.png",
    },
    amount: 18900.0,
    currency: "USD",
    status: "processing",
    method: "bank_transfer",
    gateway: "adyen",
    country: "China",
    createdAt: "2024-11-26T15:00:00Z",
    fee: 37.8,
    net: 18862.2,
    riskScore: 22,
    description: "Enterprise Deployment",
  },
  {
    id: "txn_14",
    reference: "PAY-2024-00014",
    customer: {
      name: "Maria Santos",
      email: "m.santos@latam-corp.br",
      avatar: "https://github.com/rauchg.png",
    },
    amount: 780.0,
    currency: "USD",
    status: "completed",
    method: "credit_card",
    gateway: "braintree",
    country: "Brazil",
    createdAt: "2024-11-26T13:25:00Z",
    completedAt: "2024-11-26T13:25:40Z",
    fee: 23.4,
    net: 756.6,
    riskScore: 8,
    description: "Pro Plan - Monthly",
  },
  {
    id: "txn_15",
    reference: "PAY-2024-00015",
    customer: {
      name: "Robert Miller",
      email: "r.miller@enterprise.us",
      avatar: "https://github.com/timneutkens.png",
    },
    amount: 45000.0,
    currency: "USD",
    status: "completed",
    method: "ach",
    gateway: "stripe",
    country: "United States",
    createdAt: "2024-11-26T10:00:00Z",
    completedAt: "2024-11-26T10:05:00Z",
    fee: 25.0,
    net: 44975.0,
    riskScore: 2,
    description: "Annual Enterprise Contract",
  },
  {
    id: "txn_16",
    reference: "PAY-2024-00016",
    customer: {
      name: "Sophie Laurent",
      email: "s.laurent@paris-digital.fr",
      avatar: "https://github.com/shuding.png",
    },
    amount: 1650.0,
    currency: "USD",
    status: "completed",
    method: "credit_card",
    gateway: "stripe",
    country: "France",
    createdAt: "2024-11-26T08:15:00Z",
    completedAt: "2024-11-26T08:15:25Z",
    fee: 49.5,
    net: 1600.5,
    riskScore: 6,
    description: "Team Plan - Quarterly",
  },
  {
    id: "txn_17",
    reference: "PAY-2024-00017",
    customer: {
      name: "Ahmed Al-Rashid",
      email: "a.alrashid@gulf-enterprises.sa",
      avatar: "https://github.com/vercel.png",
    },
    amount: 9200.0,
    currency: "USD",
    status: "failed",
    method: "credit_card",
    gateway: "adyen",
    country: "Saudi Arabia",
    createdAt: "2024-11-25T17:40:00Z",
    fee: 0,
    net: 0,
    riskScore: 82,
    description: "Card Declined - Limit Exceeded",
  },
  {
    id: "txn_18",
    reference: "PAY-2024-00018",
    customer: {
      name: "Emily Brown",
      email: "e.brown@aussie-tech.au",
      avatar: "https://github.com/nextjs.png",
    },
    amount: 3350.0,
    currency: "USD",
    status: "completed",
    method: "debit_card",
    gateway: "stripe",
    country: "Australia",
    createdAt: "2024-11-25T06:30:00Z",
    completedAt: "2024-11-25T06:30:35Z",
    fee: 100.5,
    net: 3249.5,
    riskScore: 9,
    description: "Professional Plan - Annual",
  },
  {
    id: "txn_19",
    reference: "PAY-2024-00019",
    customer: {
      name: "Yuki Nakamura",
      email: "y.nakamura@osaka-inc.jp",
      avatar: "https://github.com/tailwindlabs.png",
    },
    amount: 2890.0,
    currency: "USD",
    status: "refunded",
    method: "credit_card",
    gateway: "stripe",
    country: "Japan",
    createdAt: "2024-11-25T04:20:00Z",
    completedAt: "2024-11-25T04:21:00Z",
    fee: -86.7,
    net: -2803.3,
    riskScore: 18,
    description: "Refund - Duplicate Charge",
  },
  {
    id: "txn_20",
    reference: "PAY-2024-00020",
    customer: {
      name: "Carlos Mendez",
      email: "c.mendez@mexico-digital.mx",
      avatar: "https://github.com/radix-ui.png",
    },
    amount: 560.0,
    currency: "USD",
    status: "completed",
    method: "digital_wallet",
    gateway: "paypal",
    country: "Mexico",
    createdAt: "2024-11-24T20:15:00Z",
    completedAt: "2024-11-24T20:15:10Z",
    fee: 16.8,
    net: 543.2,
    riskScore: 5,
    description: "Starter Plan - Monthly",
  },
  {
    id: "txn_21",
    reference: "PAY-2024-00021",
    customer: {
      name: "Anna Kowalski",
      email: "a.kowalski@warsaw-tech.pl",
      avatar: "https://github.com/shadcn.png",
    },
    amount: 4100.0,
    currency: "USD",
    status: "completed",
    method: "bank_transfer",
    gateway: "adyen",
    country: "Poland",
    createdAt: "2024-11-24T14:50:00Z",
    completedAt: "2024-11-24T14:55:00Z",
    fee: 8.2,
    net: 4091.8,
    riskScore: 7,
    description: "Team Plan - Annual",
  },
  {
    id: "txn_22",
    reference: "PAY-2024-00022",
    customer: {
      name: "Michael O'Brien",
      email: "m.obrien@dublin-software.ie",
      avatar: "https://github.com/leerob.png",
    },
    amount: 1890.0,
    currency: "USD",
    status: "processing",
    method: "credit_card",
    gateway: "braintree",
    country: "Ireland",
    createdAt: "2024-11-24T11:30:00Z",
    fee: 56.7,
    net: 1833.3,
    riskScore: 14,
    description: "Pro Plan - Quarterly",
  },
  {
    id: "txn_23",
    reference: "PAY-2024-00023",
    customer: {
      name: "Fatima Al-Zahra",
      email: "f.alzahra@cairo-innovations.eg",
      avatar: "https://github.com/evilrabbit.png",
    },
    amount: 720.0,
    currency: "USD",
    status: "completed",
    method: "credit_card",
    gateway: "stripe",
    country: "Egypt",
    createdAt: "2024-11-24T09:10:00Z",
    completedAt: "2024-11-24T09:10:30Z",
    fee: 21.6,
    net: 698.4,
    riskScore: 11,
    description: "Pro Plan - Monthly",
  },
  {
    id: "txn_24",
    reference: "PAY-2024-00024",
    customer: {
      name: "Thomas Mueller",
      email: "t.mueller@berlin-tech.de",
      avatar: "https://github.com/rauchg.png",
    },
    amount: 7500.0,
    currency: "USD",
    status: "completed",
    method: "bank_transfer",
    gateway: "adyen",
    country: "Germany",
    createdAt: "2024-11-23T16:45:00Z",
    completedAt: "2024-11-23T16:50:00Z",
    fee: 15.0,
    net: 7485.0,
    riskScore: 4,
    description: "Enterprise Plan - Quarterly",
  },
  {
    id: "txn_25",
    reference: "PAY-2024-00025",
    customer: {
      name: "Raj Patel",
      email: "r.patel@mumbai-ventures.in",
      avatar: "https://github.com/timneutkens.png",
    },
    amount: 1100.0,
    currency: "USD",
    status: "disputed",
    method: "credit_card",
    gateway: "stripe",
    country: "India",
    createdAt: "2024-11-23T12:20:00Z",
    completedAt: "2024-11-23T12:20:45Z",
    fee: 33.0,
    net: 1067.0,
    riskScore: 58,
    description: "Disputed - Service Not Received",
  },
];
